apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  namespace: default
  name: autosd-microshift
export:
  qemu:
    type: jumpstarter_driver_qemu.driver.Qemu
    config:
      arch: aarch64
      smp: 4
      mem: 4G
      disk_size: 20G
      username: root
      password: testpassword
      hostfwd:
        ssh:
          hostport: 2222
          guestport: 22
        # maps exporter-host:16443 to VM:6443 (QM-published MicroShift API)
        apiserver:
          hostport: 16443
          guestport: 6443
